/* ========================================================================
 * genovo_ffi.h - Auto-generated by cbindgen. DO NOT EDIT.
 *
 * C API for the Genovo game engine.
 * ======================================================================== */


#ifndef GENOVO_FFI_H
#define GENOVO_FFI_H

/* Generated with cbindgen:0.27.0 */

/* WARNING: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace  {
#endif  // __cplusplus

/**
 * Integer result code returned by all FFI functions.
 *
 * Zero means success; negative values indicate specific error categories.
 * When a non-zero code is returned the caller should inspect the thread-local
 * error string via `genovo_get_last_error()` for a human-readable message.
 */
#define FFI_OK 0

#define FFI_ERR_NULL_POINTER -1

#define FFI_ERR_INVALID_HANDLE -2

#define FFI_ERR_INTERNAL -3

#define FFI_ERR_INVALID_PARAMETER -4

#define FFI_ERR_OUT_OF_MEMORY -5

#define FFI_ERR_NOT_IMPLEMENTED -6

#define FFI_ERR_PANIC -7

#define FFI_ERR_AUDIO_DECODE -8

#define FFI_ERR_AUDIO_PLAYBACK -9

#define FFI_ERR_PHYSICS_BODY -10

#ifdef __cplusplus
}  // namespace 
#endif  // __cplusplus

#endif  /* GENOVO_FFI_H */

/* End of genovo_ffi.h */
