/* ========================================================================
 * genovo_ffi.h - Auto-generated by cbindgen. DO NOT EDIT.
 *
 * C API for the Genovo game engine.
 * ======================================================================== */


#ifndef GENOVO_FFI_H
#define GENOVO_FFI_H

/* Generated with cbindgen:0.27.0 */

/* WARNING: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace  {
#endif  // __cplusplus

/**
 * Integer result code returned by all FFI functions.
 *
 * Zero means success; negative values indicate specific error categories.
 * When a non-zero code is returned the caller should inspect the thread-local
 * error string via `genovo_get_last_error()` for a human-readable message.
 */
#define FFI_OK 0

#define FFI_ERR_NULL_POINTER -1

#define FFI_ERR_INVALID_HANDLE -2

#define FFI_ERR_INTERNAL -3

#define FFI_ERR_INVALID_PARAMETER -4

#define FFI_ERR_OUT_OF_MEMORY -5

#define FFI_ERR_NOT_IMPLEMENTED -6

#define FFI_ERR_PANIC -7

#define FFI_ERR_AUDIO_DECODE -8

#define FFI_ERR_AUDIO_PLAYBACK -9

#define FFI_ERR_PHYSICS_BODY -10

/**
 * Type alias used by all FFI functions.  `0` is success, negative is error.
 */
typedef int32_t FfiResult;

/**
 * 3-component floating-point vector in C-compatible layout.
 */
typedef struct FfiVec3 {
  float x;
  float y;
  float z;
} FfiVec3;
/**
 * The zero vector.
 */
#define FfiVec3_ZERO (FfiVec3){ .x = 0.0, .y = 0.0, .z = 0.0 }
/**
 * The unit vector (1, 1, 1).
 */
#define FfiVec3_ONE (FfiVec3){ .x = 1.0, .y = 1.0, .z = 1.0 }

/**
 * Quaternion in C-compatible layout (x, y, z, w order).
 */
typedef struct FfiQuat {
  float x;
  float y;
  float z;
  float w;
} FfiQuat;
/**
 * The identity quaternion (no rotation).
 */
#define FfiQuat_IDENTITY (FfiQuat){ .x = 0.0, .y = 0.0, .z = 0.0, .w = 1.0 }

/**
 * Rigid body descriptor passed across the FFI boundary.
 *
 * `body_type` encoding: 0 = Static, 1 = Dynamic, 2 = Kinematic.
 */
typedef struct FfiRigidBodyDesc {
  /**
   * 0 = Static, 1 = Dynamic, 2 = Kinematic.
   */
  uint8_t body_type;
  /**
   * Mass in kilograms (ignored for static bodies).
   */
  float mass;
  /**
   * Coulomb friction coefficient [0, 1].
   */
  float friction;
  /**
   * Coefficient of restitution (bounciness) [0, 1].
   */
  float restitution;
  /**
   * Linear damping factor.
   */
  float linear_damping;
  /**
   * Angular damping factor.
   */
  float angular_damping;
  /**
   * Initial position.
   */
  struct FfiVec3 position;
  /**
   * Initial rotation.
   */
  struct FfiQuat rotation;
  /**
   * Whether the body starts awake (1) or sleeping (0).
   */
  uint8_t is_awake;
  /**
   * Whether continuous collision detection is enabled.
   */
  uint8_t ccd_enabled;
  /**
   * Padding / reserved for future use.
   */
  uint8_t _reserved[2];
} FfiRigidBodyDesc;

/**
 * Result of a physics raycast, returned to C callers.
 */
typedef struct FfiRaycastResult {
  /**
   * World-space hit position.
   */
  struct FfiVec3 point;
  /**
   * Surface normal at the hit point.
   */
  struct FfiVec3 normal;
  /**
   * Distance from the ray origin to the hit point.
   */
  float distance;
  /**
   * Handle of the rigid body that was hit.  `0` typically means invalid.
   */
  uint64_t body_handle;
} FfiRaycastResult;

/**
 * Transform (position + rotation + scale) in C-compatible layout.
 */
typedef struct FfiTransform {
  struct FfiVec3 position;
  struct FfiQuat rotation;
  struct FfiVec3 scale;
} FfiTransform;
/**
 * An identity transform: origin position, no rotation, unit scale.
 */
#define FfiTransform_IDENTITY (FfiTransform){ .position = FfiVec3_ZERO, .rotation = FfiQuat_IDENTITY, .scale = FfiVec3_ONE }

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Retrieve the last error message set on the current thread.
 *
 * Returns a null pointer if no error has been recorded since the last call to
 * `genovo_clear_error()` (or if no error has ever been set).
 *
 * # Safety
 *
 * The returned pointer is valid until the next FFI call on the **same thread**
 * that modifies the error state. Callers must copy the string if they need to
 * keep it beyond that point.
 */
const char *genovo_get_last_error(void);

/**
 * Clear the thread-local error state.
 */
void genovo_clear_error(void);

/**
 * Create a new physics world with the specified gravity vector.
 *
 * Returns a heap-allocated `PhysicsWorld` as an opaque pointer. The caller
 * **must** eventually free it with `genovo_physics_world_destroy`.
 *
 * Returns null on failure (check `genovo_get_last_error`).
 *
 * # Safety
 *
 * Caller owns the returned pointer and must not use it after calling
 * `genovo_physics_world_destroy`.
 */
PhysicsWorld *genovo_physics_world_create(float gravity_x, float gravity_y, float gravity_z);

/**
 * Destroy a physics world previously created with `genovo_physics_world_create`.
 *
 * After this call the pointer is invalid and must not be used.
 *
 * # Safety
 *
 * `world` must be a valid pointer returned by `genovo_physics_world_create`
 * and must not have been previously destroyed.
 */
FfiResult genovo_physics_world_destroy(PhysicsWorld *world);

/**
 * Advance the physics simulation by `dt` seconds.
 *
 * # Safety
 *
 * `world` must be a valid, non-null pointer to a live `PhysicsWorld`.
 */
FfiResult genovo_physics_world_step(PhysicsWorld *world, float dt);

/**
 * Set the gravity vector on an existing physics world.
 *
 * # Safety
 *
 * `world` must be a valid, non-null pointer.
 */
FfiResult genovo_physics_world_set_gravity(PhysicsWorld *world, float x, float y, float z);

/**
 * Add a rigid body to the physics world.
 *
 * `desc` must point to a valid `FfiRigidBodyDesc`.
 *
 * Returns the body handle as a `u64`. On failure returns `0` and sets the
 * error string.
 *
 * # Safety
 *
 * Both `world` and `desc` must be valid, non-null pointers.
 */
uint64_t genovo_physics_add_body(PhysicsWorld *world, const struct FfiRigidBodyDesc *desc);

/**
 * Remove a rigid body from the physics world by handle.
 *
 * # Safety
 *
 * `world` must be a valid, non-null pointer. `handle` must be a value
 * previously returned by `genovo_physics_add_body`.
 */
FfiResult genovo_physics_remove_body(PhysicsWorld *world, uint64_t handle);

/**
 * Set the world-space position of a rigid body.
 *
 * # Safety
 *
 * `world` must be valid and non-null. `handle` must refer to an existing body.
 */
FfiResult genovo_physics_set_position(PhysicsWorld *world,
                                      uint64_t handle,
                                      float x,
                                      float y,
                                      float z);

/**
 * Read the world-space position of a rigid body into caller-supplied floats.
 *
 * `out_x`, `out_y`, `out_z` must each point to a writable `f32`.
 *
 * # Safety
 *
 * All pointer arguments must be valid and non-null.
 */
FfiResult genovo_physics_get_position(PhysicsWorld *world,
                                      uint64_t handle,
                                      float *out_x,
                                      float *out_y,
                                      float *out_z);

/**
 * Apply a force (in world coordinates) to a rigid body.
 *
 * The force is applied at the center of mass for the current simulation step.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_add_force(PhysicsWorld *world,
                                   uint64_t handle,
                                   float fx,
                                   float fy,
                                   float fz);

/**
 * Cast a ray into the physics world and write up to `max_results` hits into
 * the caller-provided buffer.
 *
 * Returns the number of hits written. On error, returns `0` and sets the
 * error string.
 *
 * # Parameters
 *
 * - `ox, oy, oz` -- ray origin in world space.
 * - `dx, dy, dz` -- ray direction (will be normalized internally).
 * - `max_dist`    -- maximum ray travel distance.
 * - `out_results` -- pointer to an array of `FfiRaycastResult` with room for
 *                    at least `max_results` entries.
 * - `max_results` -- capacity of `out_results`.
 *
 * # Safety
 *
 * `world` and `out_results` must be valid, non-null pointers. `out_results`
 * must have room for `max_results` elements.
 */
uint32_t genovo_physics_raycast(PhysicsWorld *world,
                                float ox,
                                float oy,
                                float oz,
                                float dx,
                                float dy,
                                float dz,
                                float max_dist,
                                struct FfiRaycastResult *out_results,
                                uint32_t max_results);

/**
 * Add a box collider to a rigid body.
 *
 * `half_x`, `half_y`, `half_z` are the half-extents of the box shape.
 *
 * Returns `0` on success, negative error code on failure.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_add_box_collider(PhysicsWorld *world,
                                          uint64_t body_handle,
                                          float half_x,
                                          float half_y,
                                          float half_z,
                                          float friction,
                                          float restitution);

/**
 * Add a sphere collider to a rigid body.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_add_sphere_collider(PhysicsWorld *world,
                                             uint64_t body_handle,
                                             float radius,
                                             float friction,
                                             float restitution);

/**
 * Add a capsule collider to a rigid body.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_add_capsule_collider(PhysicsWorld *world,
                                              uint64_t body_handle,
                                              float radius,
                                              float half_height,
                                              float friction,
                                              float restitution);

/**
 * Get the linear velocity of a rigid body.
 *
 * # Safety
 *
 * All pointer arguments must be valid and non-null.
 */
FfiResult genovo_physics_get_velocity(PhysicsWorld *world,
                                      uint64_t handle,
                                      float *out_vx,
                                      float *out_vy,
                                      float *out_vz);

/**
 * Set the linear velocity of a rigid body.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_set_velocity(PhysicsWorld *world,
                                      uint64_t handle,
                                      float vx,
                                      float vy,
                                      float vz);

/**
 * Get the rotation (as a quaternion) of a rigid body.
 *
 * # Safety
 *
 * All pointer arguments must be valid and non-null.
 */
FfiResult genovo_physics_get_rotation(PhysicsWorld *world,
                                      uint64_t handle,
                                      float *out_qx,
                                      float *out_qy,
                                      float *out_qz,
                                      float *out_qw);

/**
 * Set the rotation (as a quaternion) of a rigid body.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
FfiResult genovo_physics_set_rotation(PhysicsWorld *world,
                                      uint64_t handle,
                                      float qx,
                                      float qy,
                                      float qz,
                                      float qw);

/**
 * Get the full transform (position + rotation) of a rigid body.
 *
 * # Safety
 *
 * `world` and `out_transform` must be valid, non-null pointers.
 */
FfiResult genovo_physics_get_transform(PhysicsWorld *world,
                                       uint64_t handle,
                                       struct FfiTransform *out_transform);

/**
 * Query the number of rigid bodies currently in the world.
 *
 * # Safety
 *
 * `world` must be valid and non-null. `out_count` must point to writable
 * memory.
 */
FfiResult genovo_physics_body_count(PhysicsWorld *world, uint32_t *out_count);

/**
 * Create a new software audio mixer.
 *
 * Returns a heap-allocated `SoftwareMixer` as an opaque pointer. The caller
 * **must** eventually free it with `genovo_audio_mixer_destroy`.
 *
 * Returns null on failure.
 *
 * # Safety
 *
 * Caller owns the returned pointer.
 */
SoftwareMixer *genovo_audio_mixer_create(void);

/**
 * Destroy a software audio mixer previously created with
 * `genovo_audio_mixer_create`.
 *
 * # Safety
 *
 * `mixer` must be a valid pointer returned by `genovo_audio_mixer_create` and
 * must not have been previously destroyed.
 */
FfiResult genovo_audio_mixer_destroy(SoftwareMixer *mixer);

/**
 * Update the audio mixer, advancing internal state by `dt` seconds.
 *
 * This should be called once per frame (or at the audio-thread tick rate).
 *
 * # Safety
 *
 * `mixer` must be a valid, non-null pointer.
 */
FfiResult genovo_audio_mixer_update(SoftwareMixer *mixer, float dt);

/**
 * Load an audio clip from raw WAV data in memory.
 *
 * `data` must point to `len` bytes of valid WAV-encoded audio. The data is
 * copied internally; the caller may free the original buffer after this call
 * returns.
 *
 * Returns a heap-allocated `AudioClip` pointer, or null on failure.
 *
 * # Safety
 *
 * `data` must be a valid pointer to at least `len` bytes of readable memory.
 */
AudioClip *genovo_audio_clip_from_wav(const uint8_t *data, uintptr_t len);

/**
 * Destroy an audio clip previously created with `genovo_audio_clip_from_wav`.
 *
 * # Safety
 *
 * `clip` must be a valid pointer returned by `genovo_audio_clip_from_wav` and
 * must not have been previously destroyed.
 */
FfiResult genovo_audio_clip_destroy(AudioClip *clip);

/**
 * Play an audio clip through the mixer.
 *
 * # Parameters
 *
 * - `mixer`   -- pointer to the software mixer.
 * - `clip`    -- pointer to the audio clip to play.
 * - `volume`  -- playback volume, where `1.0` is full volume.
 * - `pitch`   -- playback pitch multiplier (`1.0` = normal speed).
 * - `looping` -- `1` to loop, `0` for one-shot.
 *
 * Returns a `u64` mixer handle that can be used with `genovo_audio_stop` and
 * `genovo_audio_set_volume`. Returns `0` on failure.
 *
 * # Safety
 *
 * `mixer` and `clip` must be valid, non-null pointers.
 */
uint64_t genovo_audio_play(SoftwareMixer *mixer,
                           const AudioClip *clip,
                           float volume,
                           float pitch,
                           uint8_t looping);

/**
 * Stop a sound that is currently playing.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null. `handle` must have been returned by a
 * previous call to `genovo_audio_play`.
 */
FfiResult genovo_audio_stop(SoftwareMixer *mixer, uint64_t handle);

/**
 * Set the volume of a currently-playing sound.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_set_volume(SoftwareMixer *mixer, uint64_t handle, float volume);

/**
 * Set the pitch of a currently-playing sound.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_set_pitch(SoftwareMixer *mixer, uint64_t handle, float pitch);

/**
 * Pause a currently-playing sound.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_pause(SoftwareMixer *mixer, uint64_t handle);

/**
 * Resume a paused sound.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_resume(SoftwareMixer *mixer, uint64_t handle);

/**
 * Query whether a sound is currently playing (not paused, not finished).
 *
 * Writes `1` to `out_playing` if playing, `0` otherwise.
 *
 * # Safety
 *
 * `mixer` and `out_playing` must be valid, non-null pointers.
 */
FfiResult genovo_audio_is_playing(SoftwareMixer *mixer, uint64_t handle, uint8_t *out_playing);

/**
 * Set the master volume of the mixer (affects all playing sounds).
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_set_master_volume(SoftwareMixer *mixer, float volume);

/**
 * Stop all currently playing sounds on the mixer.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_stop_all(SoftwareMixer *mixer);

/**
 * Set the 3D position of the audio listener (for spatial audio).
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_set_listener_position(SoftwareMixer *mixer, float x, float y, float z);

/**
 * Set the full 3D listener transform (position, forward, up) for spatial
 * audio.
 *
 * # Safety
 *
 * `mixer` must be valid and non-null.
 */
FfiResult genovo_audio_set_listener_orientation(SoftwareMixer *mixer,
                                                float pos_x,
                                                float pos_y,
                                                float pos_z,
                                                float fwd_x,
                                                float fwd_y,
                                                float fwd_z,
                                                float up_x,
                                                float up_y,
                                                float up_z);

/**
 * Allocate `size` bytes of memory aligned to `align` using the Rust global
 * allocator.
 *
 * The returned pointer must be freed with `genovo_free` using the **same**
 * `size` and `align` values.
 *
 * Returns null on failure (check `genovo_get_last_error`).
 *
 * # Safety
 *
 * - `size` must be greater than zero.
 * - `align` must be a power of two and non-zero.
 * - The caller is responsible for eventually freeing the allocation.
 */
uint8_t *genovo_alloc(uintptr_t size, uintptr_t align);

/**
 * Free memory previously allocated with `genovo_alloc`.
 *
 * # Safety
 *
 * - `ptr` must have been returned by `genovo_alloc` with the **same** `size`
 *   and `align` values.
 * - `ptr` must not have been freed already.
 * - After this call, `ptr` is dangling and must not be used.
 */
void genovo_free(uint8_t *ptr, uintptr_t size, uintptr_t align);

/**
 * Reallocate a block previously returned by `genovo_alloc`.
 *
 * The alignment must match the original allocation. If the new size is
 * larger, the extra bytes are zeroed.
 *
 * Returns a new pointer (the old one is invalid). Returns null on failure,
 * in which case the original allocation is **not** freed.
 *
 * # Safety
 *
 * - `ptr` must have been returned by `genovo_alloc` or `genovo_realloc`.
 * - `old_size` and `align` must match the current allocation.
 */
uint8_t *genovo_realloc(uint8_t *ptr, uintptr_t old_size, uintptr_t new_size, uintptr_t align);

/**
 * Return the packed version number of the FFI layer.
 *
 * Bits 31..22 = major, 21..12 = minor, 11..0 = patch.
 */
uint32_t genovo_version(void);

/**
 * Return the major version component.
 */
uint32_t genovo_version_major(void);

/**
 * Return the minor version component.
 */
uint32_t genovo_version_minor(void);

/**
 * Return the patch version component.
 */
uint32_t genovo_version_patch(void);

/**
 * Return a static C string describing the engine version.
 *
 * The returned pointer is valid for the lifetime of the process.
 */
const char *genovo_version_string(void);

/**
 * Free a C string that was allocated by the FFI layer.
 *
 * Some FFI functions return dynamically-allocated C strings. This function
 * frees them.
 *
 * # Safety
 *
 * `ptr` must be a C string allocated by this FFI layer, or null (in which
 * case this is a no-op).
 */
void genovo_string_free(char *ptr);

/**
 * Global initialization of the Genovo engine.
 *
 * Must be called exactly once before using any other FFI function (except
 * version queries, which are always safe). Initializes logging, global
 * allocator hooks, and other subsystem prerequisites.
 *
 * Returns `FFI_OK` on success, or a negative error code on failure.
 */
FfiResult genovo_init(void);

/**
 * Global shutdown of the Genovo engine.
 *
 * Should be called when the host application is done using the engine.
 * After this call, no other FFI functions should be invoked except
 * `genovo_init`.
 *
 * # Safety
 *
 * All engine objects (worlds, mixers, clips, etc.) must have been destroyed
 * before calling this function.
 */
FfiResult genovo_shutdown(void);

/**
 * Create a new ECS world.
 *
 * Returns a heap-allocated `EcsWorld` as an opaque pointer. The caller must
 * eventually free it with `genovo_ecs_world_destroy`.
 *
 * # Safety
 *
 * Caller owns the returned pointer.
 */
EcsWorld *genovo_ecs_world_create(void);

/**
 * Destroy an ECS world previously created with `genovo_ecs_world_create`.
 *
 * # Safety
 *
 * `world` must be a valid pointer and must not have been previously destroyed.
 */
FfiResult genovo_ecs_world_destroy(EcsWorld *world);

/**
 * Create an entity in the ECS world.
 *
 * Returns the entity ID as a `u64`. Returns `0` on failure.
 *
 * # Safety
 *
 * `world` must be valid and non-null.
 */
uint64_t genovo_ecs_create_entity(EcsWorld *world);

/**
 * Destroy an entity in the ECS world.
 *
 * # Safety
 *
 * `world` must be valid and non-null. `entity_id` must be a valid entity.
 */
FfiResult genovo_ecs_destroy_entity(EcsWorld *world, uint64_t entity_id);

/**
 * Query the number of live entities in the ECS world.
 *
 * # Safety
 *
 * `world` and `out_count` must be valid, non-null pointers.
 */
FfiResult genovo_ecs_entity_count(EcsWorld *world, uint32_t *out_count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace 
#endif  // __cplusplus

#endif  /* GENOVO_FFI_H */

/* End of genovo_ffi.h */
