// engine/render/src/billboard.rs
//
// Billboard impostor rendering system for the Genovo engine.
//
// Replaces distant meshes with camera-facing textured quads. Supports multiple
// facing modes (screen-aligned, world-Y, axis-aligned, velocity-stretched),
// multi-angle impostor atlases with octahedral normal mapping, instanced
// batched rendering with back-to-front sorting, and automatic billboard cloud
// generation from complex meshes.

use crate::mesh::{Mesh, MeshBuilder, Vertex, AABB};
use glam::{Mat3, Mat4, Quat, Vec2, Vec3, Vec4};
use std::cmp::Ordering;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum number of billboards in a single batch.
pub const MAX_BILLBOARDS_PER_BATCH: usize = 65_536;

/// Default atlas tile count per axis (8 angles = 8x8 = 64 views).
pub const DEFAULT_IMPOSTOR_ANGLES: u32 = 8;

/// Maximum atlas tile count per axis.
pub const MAX_IMPOSTOR_ANGLES: u32 = 32;

/// Default soft-particle fade distance in world units.
pub const DEFAULT_SOFT_PARTICLE_FADE: f32 = 0.5;

/// Number of billboard planes generated by the cloud algorithm.
pub const DEFAULT_CLOUD_PLANES: usize = 8;

// ---------------------------------------------------------------------------
// BillboardFacingMode
// ---------------------------------------------------------------------------

/// Determines how a billboard orients itself relative to the camera.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum BillboardFacingMode {
    /// Billboard always faces the camera with no tilt; it is parallel to the
    /// screen plane. Good for particles, UI elements, and lens flares.
    ScreenAligned,
    /// Billboard rotates around the world Y axis only, staying upright. Good
    /// for trees, lampposts, and standing characters.
    WorldY,
    /// Billboard rotates around a custom axis. The axis is the rotation axis,
    /// and the billboard attempts to face the camera while constrained.
    AxisAligned(Vec3),
    /// Billboard is stretched along its velocity vector. The quad is elongated
    /// in the direction of motion, producing a streak effect. Good for sparks,
    /// rain drops, and tracer rounds.
    Velocity,
}

impl Default for BillboardFacingMode {
    fn default() -> Self {
        Self::ScreenAligned
    }
}

// ---------------------------------------------------------------------------
// Billboard
// ---------------------------------------------------------------------------

/// A single billboard instance with position, size, texture, and facing mode.
#[derive(Debug, Clone)]
pub struct Billboard {
    /// World-space position (centre of the billboard).
    pub position: Vec3,
    /// Half-width and half-height in world units.
    pub size: Vec2,
    /// Texture handle (index into the material system or atlas).
    pub texture_handle: u32,
    /// Facing mode.
    pub facing_mode: BillboardFacingMode,
    /// Tint colour (RGBA, premultiplied alpha).
    pub color: Vec4,
    /// Rotation angle in radians around the billboard's facing axis.
    pub rotation: f32,
    /// UV rectangle within the atlas: (u_min, v_min, u_max, v_max).
    pub uv_rect: Vec4,
    /// Velocity vector (only used when facing_mode is `Velocity`).
    pub velocity: Vec3,
    /// Sort depth (computed each frame during batching).
    pub sort_depth: f32,
    /// Custom data channel (shader-interpreted: e.g. animation frame, LOD fade).
    pub custom_data: Vec4,
}

impl Default for Billboard {
    fn default() -> Self {
        Self {
            position: Vec3::ZERO,
            size: Vec2::splat(1.0),
            texture_handle: 0,
            facing_mode: BillboardFacingMode::ScreenAligned,
            color: Vec4::ONE,
            rotation: 0.0,
            uv_rect: Vec4::new(0.0, 0.0, 1.0, 1.0),
            velocity: Vec3::ZERO,
            sort_depth: 0.0,
            custom_data: Vec4::ZERO,
        }
    }
}

impl Billboard {
    /// Create a simple screen-aligned billboard.
    pub fn new(position: Vec3, size: Vec2, texture_handle: u32) -> Self {
        Self {
            position,
            size,
            texture_handle,
            ..Default::default()
        }
    }

    /// Create a billboard with a specific facing mode.
    pub fn with_facing(mut self, mode: BillboardFacingMode) -> Self {
        self.facing_mode = mode;
        self
    }

    /// Set the tint colour.
    pub fn with_color(mut self, color: Vec4) -> Self {
        self.color = color;
        self
    }

    /// Set the rotation angle.
    pub fn with_rotation(mut self, radians: f32) -> Self {
        self.rotation = radians;
        self
    }

    /// Set the velocity (for `Velocity` facing mode).
    pub fn with_velocity(mut self, velocity: Vec3) -> Self {
        self.velocity = velocity;
        self
    }

    /// Set the UV rectangle.
    pub fn with_uv_rect(mut self, u_min: f32, v_min: f32, u_max: f32, v_max: f32) -> Self {
        self.uv_rect = Vec4::new(u_min, v_min, u_max, v_max);
        self
    }

    /// Compute the sort depth given a view matrix.
    pub fn compute_sort_depth(&mut self, view: &Mat4) {
        let view_pos = *view * self.position.extend(1.0);
        self.sort_depth = view_pos.z;
    }
}

// ---------------------------------------------------------------------------
// BillboardVertex
// ---------------------------------------------------------------------------

/// Per-vertex data for a billboard quad. Packed for GPU upload.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct BillboardVertex {
    /// World-space position of this vertex.
    pub position: [f32; 3],
    /// Texture coordinates.
    pub uv: [f32; 2],
    /// RGBA colour (premultiplied alpha).
    pub color: [f32; 4],
    /// Billboard size (width, height) for instanced rendering.
    pub size: [f32; 2],
    /// Rotation angle in radians.
    pub rotation: f32,
}

impl BillboardVertex {
    /// Byte size of one vertex.
    pub const SIZE: usize = std::mem::size_of::<Self>();

    /// Create a new billboard vertex.
    pub fn new(position: Vec3, uv: Vec2, color: Vec4, size: Vec2, rotation: f32) -> Self {
        Self {
            position: position.to_array(),
            uv: uv.to_array(),
            color: color.to_array(),
            size: size.to_array(),
            rotation,
        }
    }
}

// ---------------------------------------------------------------------------
// BillboardQuadBuilder
// ---------------------------------------------------------------------------

/// Generates the 4 vertices of a camera-facing quad for a single billboard.
pub struct BillboardQuadBuilder;

impl BillboardQuadBuilder {
    /// Generate the 4 corner positions and 6 indices for a billboard quad.
    ///
    /// The quad is centred at `position`, with half-extents `size`, oriented
    /// according to `facing_mode` relative to the camera.
    ///
    /// Returns `(positions[4], uvs[4])`.
    pub fn build_quad(
        billboard: &Billboard,
        camera_position: Vec3,
        camera_right: Vec3,
        camera_up: Vec3,
        camera_forward: Vec3,
    ) -> ([Vec3; 4], [Vec2; 4]) {
        let (right, up) = Self::compute_axes(
            billboard,
            camera_position,
            camera_right,
            camera_up,
            camera_forward,
        );

        let hw = billboard.size.x;
        let hh = billboard.size.y;

        // Apply rotation.
        let (right, up) = if billboard.rotation.abs() > 1e-6 {
            let cos_r = billboard.rotation.cos();
            let sin_r = billboard.rotation.sin();
            let rotated_right = right * cos_r + up * sin_r;
            let rotated_up = -right * sin_r + up * cos_r;
            (rotated_right, rotated_up)
        } else {
            (right, up)
        };

        let p = billboard.position;
        let positions = [
            p - right * hw - up * hh, // bottom-left
            p + right * hw - up * hh, // bottom-right
            p + right * hw + up * hh, // top-right
            p - right * hw + up * hh, // top-left
        ];

        let uv_rect = billboard.uv_rect;
        let uvs = [
            Vec2::new(uv_rect.x, uv_rect.w), // bottom-left
            Vec2::new(uv_rect.z, uv_rect.w), // bottom-right
            Vec2::new(uv_rect.z, uv_rect.y), // top-right
            Vec2::new(uv_rect.x, uv_rect.y), // top-left
        ];

        (positions, uvs)
    }

    /// Compute the right and up axes for a billboard given its facing mode.
    fn compute_axes(
        billboard: &Billboard,
        camera_position: Vec3,
        camera_right: Vec3,
        camera_up: Vec3,
        camera_forward: Vec3,
    ) -> (Vec3, Vec3) {
        match billboard.facing_mode {
            BillboardFacingMode::ScreenAligned => {
                // Use the camera's screen axes directly.
                (camera_right, camera_up)
            }

            BillboardFacingMode::WorldY => {
                // The up axis is always world Y. The right axis is the cross
                // product of world Y and the direction from billboard to camera.
                let to_camera = (camera_position - billboard.position).normalize_or_zero();
                let up = Vec3::Y;
                let right = up.cross(to_camera).normalize_or_zero();
                // Handle degenerate case where camera is directly above/below.
                if right.length_squared() < 1e-6 {
                    return (camera_right, up);
                }
                (right, up)
            }

            BillboardFacingMode::AxisAligned(axis) => {
                // Constrained rotation around the given axis.
                let axis_norm = axis.normalize_or_zero();
                let to_camera = (camera_position - billboard.position).normalize_or_zero();
                // Project to_camera onto the plane perpendicular to axis.
                let projected = (to_camera - axis_norm * axis_norm.dot(to_camera)).normalize_or_zero();
                let right = axis_norm.cross(projected).normalize_or_zero();
                if right.length_squared() < 1e-6 {
                    return (camera_right, axis_norm);
                }
                (right, axis_norm)
            }

            BillboardFacingMode::Velocity => {
                // Stretch along velocity direction.
                let vel_len = billboard.velocity.length();
                if vel_len < 1e-6 {
                    // No velocity: fall back to screen-aligned.
                    return (camera_right, camera_up);
                }
                let vel_dir = billboard.velocity / vel_len;
                // The up axis is along the velocity.
                let up = vel_dir;
                // The right axis is perpendicular to velocity and view direction.
                let to_camera = (camera_position - billboard.position).normalize_or_zero();
                let right = to_camera.cross(up).normalize_or_zero();
                if right.length_squared() < 1e-6 {
                    return (camera_right, up);
                }
                (right, up)
            }
        }
    }
}

// ---------------------------------------------------------------------------
// BillboardAtlas
// ---------------------------------------------------------------------------

/// Packs multiple billboard textures into a single texture atlas.
///
/// Each atlas tile corresponds to one billboard type or one angle of a multi-
/// angle impostor. The atlas is a square texture subdivided into a regular grid.
#[derive(Debug, Clone)]
pub struct BillboardAtlas {
    /// Number of tiles along each axis.
    pub tiles_per_axis: u32,
    /// Total atlas width in pixels.
    pub atlas_width: u32,
    /// Total atlas height in pixels.
    pub atlas_height: u32,
    /// Tile width in pixels.
    pub tile_width: u32,
    /// Tile height in pixels.
    pub tile_height: u32,
    /// Number of allocated tiles.
    pub allocated_tiles: u32,
    /// Map from billboard type ID to tile index.
    pub tile_map: HashMap<u32, u32>,
    /// Padding between tiles in pixels.
    pub padding: u32,
}

impl BillboardAtlas {
    /// Create a new atlas with the given tile configuration.
    pub fn new(tiles_per_axis: u32, tile_size: u32, padding: u32) -> Self {
        let total = tile_size * tiles_per_axis + padding * (tiles_per_axis - 1);
        Self {
            tiles_per_axis,
            atlas_width: total,
            atlas_height: total,
            tile_width: tile_size,
            tile_height: tile_size,
            allocated_tiles: 0,
            tile_map: HashMap::new(),
            padding,
        }
    }

    /// Allocate a tile for a billboard type. Returns the tile index, or None if
    /// the atlas is full.
    pub fn allocate_tile(&mut self, type_id: u32) -> Option<u32> {
        if let Some(&idx) = self.tile_map.get(&type_id) {
            return Some(idx);
        }

        let max_tiles = self.tiles_per_axis * self.tiles_per_axis;
        if self.allocated_tiles >= max_tiles {
            return None;
        }

        let idx = self.allocated_tiles;
        self.allocated_tiles += 1;
        self.tile_map.insert(type_id, idx);
        Some(idx)
    }

    /// Get the UV rectangle for a tile index.
    ///
    /// Returns `(u_min, v_min, u_max, v_max)` in normalised [0, 1] coordinates.
    pub fn tile_uv_rect(&self, tile_index: u32) -> Vec4 {
        let col = tile_index % self.tiles_per_axis;
        let row = tile_index / self.tiles_per_axis;

        let tile_with_padding = self.tile_width + self.padding;
        let u_min = (col * tile_with_padding) as f32 / self.atlas_width as f32;
        let v_min = (row * tile_with_padding) as f32 / self.atlas_height as f32;
        let u_max = u_min + self.tile_width as f32 / self.atlas_width as f32;
        let v_max = v_min + self.tile_height as f32 / self.atlas_height as f32;

        Vec4::new(u_min, v_min, u_max, v_max)
    }

    /// Get the pixel rectangle for a tile index.
    pub fn tile_pixel_rect(&self, tile_index: u32) -> (u32, u32, u32, u32) {
        let col = tile_index % self.tiles_per_axis;
        let row = tile_index / self.tiles_per_axis;

        let tile_with_padding = self.tile_width + self.padding;
        let x = col * tile_with_padding;
        let y = row * tile_with_padding;

        (x, y, self.tile_width, self.tile_height)
    }

    /// Number of remaining free tiles.
    pub fn free_tile_count(&self) -> u32 {
        self.tiles_per_axis * self.tiles_per_axis - self.allocated_tiles
    }

    /// Total number of tiles.
    pub fn total_tile_count(&self) -> u32 {
        self.tiles_per_axis * self.tiles_per_axis
    }
}

// ---------------------------------------------------------------------------
// ImpostorRenderer
// ---------------------------------------------------------------------------

/// Manages multi-angle impostor rendering. An impostor captures an object from
/// N viewpoints (arranged hemispherically) and stores each view as a tile in
/// the `BillboardAtlas`. At runtime, the best-matching angle is selected based
/// on the camera direction relative to the object.
#[derive(Debug, Clone)]
pub struct ImpostorRenderer {
    /// Number of angle subdivisions around the hemisphere (azimuth).
    pub num_azimuth: u32,
    /// Number of angle subdivisions from top to bottom (elevation).
    pub num_elevation: u32,
    /// Precomputed view directions for each impostor angle.
    pub view_directions: Vec<Vec3>,
    /// Atlas tile indices for each angle. Length = num_azimuth * num_elevation.
    pub angle_tiles: Vec<u32>,
    /// Whether to use octahedral mapping for normals and depth.
    pub use_octahedral: bool,
}

impl ImpostorRenderer {
    /// Create an impostor renderer with the given angular resolution.
    pub fn new(num_azimuth: u32, num_elevation: u32) -> Self {
        let total_angles = num_azimuth * num_elevation;
        let mut view_directions = Vec::with_capacity(total_angles as usize);

        for elev in 0..num_elevation {
            let theta = std::f32::consts::FRAC_PI_2 * (1.0 - elev as f32 / num_elevation.max(1) as f32);
            let cos_theta = theta.cos();
            let sin_theta = theta.sin();

            for az in 0..num_azimuth {
                let phi = 2.0 * std::f32::consts::PI * az as f32 / num_azimuth as f32;
                let dir = Vec3::new(
                    cos_theta * phi.cos(),
                    sin_theta,
                    cos_theta * phi.sin(),
                );
                view_directions.push(dir.normalize_or_zero());
            }
        }

        Self {
            num_azimuth,
            num_elevation,
            view_directions,
            angle_tiles: vec![0; total_angles as usize],
            use_octahedral: true,
        }
    }

    /// Create an 8-angle impostor (single elevation ring at horizon level).
    pub fn new_horizontal(num_angles: u32) -> Self {
        Self::new(num_angles, 1)
    }

    /// Select the best impostor angle for the given camera-to-object direction.
    ///
    /// Returns the angle index.
    pub fn select_angle(&self, camera_to_object: Vec3) -> usize {
        let dir = camera_to_object.normalize_or_zero();
        let mut best_idx = 0;
        let mut best_dot: f32 = -2.0;

        for (i, view_dir) in self.view_directions.iter().enumerate() {
            let dot = dir.dot(*view_dir);
            if dot > best_dot {
                best_dot = dot;
                best_idx = i;
            }
        }

        best_idx
    }

    /// Select the best impostor angle and also the second-best for blending.
    ///
    /// Returns `(best_idx, second_idx, blend_factor)`.
    pub fn select_angle_blended(&self, camera_to_object: Vec3) -> (usize, usize, f32) {
        let dir = camera_to_object.normalize_or_zero();
        let mut best_idx = 0;
        let mut best_dot: f32 = -2.0;
        let mut second_idx = 0;
        let mut second_dot: f32 = -2.0;

        for (i, view_dir) in self.view_directions.iter().enumerate() {
            let dot = dir.dot(*view_dir);
            if dot > best_dot {
                second_dot = best_dot;
                second_idx = best_idx;
                best_dot = dot;
                best_idx = i;
            } else if dot > second_dot {
                second_dot = dot;
                second_idx = i;
            }
        }

        // Blend factor: 0.0 = fully best, 1.0 = fully second.
        let range = (best_dot - second_dot).max(1e-6);
        let factor = 1.0 - (best_dot - second_dot) / range.max(0.01);

        (best_idx, second_idx, factor.clamp(0.0, 1.0))
    }

    /// Get the atlas tile index for an impostor angle.
    pub fn get_tile(&self, angle_index: usize) -> u32 {
        self.angle_tiles.get(angle_index).copied().unwrap_or(0)
    }

    /// Set the atlas tile index for an impostor angle.
    pub fn set_tile(&mut self, angle_index: usize, tile_index: u32) {
        if angle_index < self.angle_tiles.len() {
            self.angle_tiles[angle_index] = tile_index;
        }
    }

    /// Total number of angles.
    pub fn total_angles(&self) -> u32 {
        self.num_azimuth * self.num_elevation
    }
}

// ---------------------------------------------------------------------------
// OctahedralMapping
// ---------------------------------------------------------------------------

/// Octahedral impostor mapping utilities for encoding normals and depth in a
/// 2D atlas tile, enabling parallax-correct rendering of impostors.
pub struct OctahedralMapping;

impl OctahedralMapping {
    /// Encode a unit direction vector to octahedral UV coordinates in [0, 1]^2.
    ///
    /// Maps a point on the unit sphere to a point on the unit square using an
    /// octahedron projection.
    pub fn encode(direction: Vec3) -> Vec2 {
        let n = direction.normalize_or_zero();
        let abs_sum = n.x.abs() + n.y.abs() + n.z.abs();
        let oct = Vec2::new(n.x, n.z) / abs_sum.max(1e-8);

        let oct = if n.y < 0.0 {
            Vec2::new(
                (1.0 - oct.y.abs()) * oct.x.signum(),
                (1.0 - oct.x.abs()) * oct.y.signum(),
            )
        } else {
            oct
        };

        // Map from [-1, 1] to [0, 1].
        oct * 0.5 + Vec2::splat(0.5)
    }

    /// Decode octahedral UV coordinates in [0, 1]^2 back to a unit direction.
    pub fn decode(uv: Vec2) -> Vec3 {
        // Map from [0, 1] to [-1, 1].
        let oct = uv * 2.0 - Vec2::ONE;

        let n = Vec3::new(oct.x, 1.0 - oct.x.abs() - oct.y.abs(), oct.y);

        let n = if n.y < 0.0 {
            Vec3::new(
                (1.0 - n.z.abs()) * n.x.signum(),
                n.y,
                (1.0 - n.x.abs()) * n.z.signum(),
            )
        } else {
            n
        };

        n.normalize_or_zero()
    }

    /// Generate the WGSL helper functions for octahedral encoding/decoding.
    pub fn wgsl_snippet() -> &'static str {
        OCTAHEDRAL_WGSL
    }
}

/// WGSL octahedral encoding/decoding functions.
const OCTAHEDRAL_WGSL: &str = r#"
fn octahedral_encode(n: vec3<f32>) -> vec2<f32> {
    let abs_sum = abs(n.x) + abs(n.y) + abs(n.z);
    var oct = vec2<f32>(n.x, n.z) / max(abs_sum, 0.00001);
    if (n.y < 0.0) {
        oct = vec2<f32>(
            (1.0 - abs(oct.y)) * sign(oct.x),
            (1.0 - abs(oct.x)) * sign(oct.y)
        );
    }
    return oct * 0.5 + 0.5;
}

fn octahedral_decode(uv: vec2<f32>) -> vec3<f32> {
    let oct = uv * 2.0 - 1.0;
    var n = vec3<f32>(oct.x, 1.0 - abs(oct.x) - abs(oct.y), oct.y);
    if (n.y < 0.0) {
        n = vec3<f32>(
            (1.0 - abs(n.z)) * sign(n.x),
            n.y,
            (1.0 - abs(n.x)) * sign(n.z)
        );
    }
    return normalize(n);
}
"#;

// ---------------------------------------------------------------------------
// BillboardBatch
// ---------------------------------------------------------------------------

/// Collects all billboards for a frame, sorts them back-to-front, and produces
/// vertex/index data for instanced quad rendering.
pub struct BillboardBatch {
    /// All billboards submitted for this frame.
    billboards: Vec<Billboard>,
    /// Generated vertex data for all billboard quads.
    vertices: Vec<BillboardVertex>,
    /// Generated index data for all billboard quads.
    indices: Vec<u32>,
    /// Whether soft-particle depth-fade is enabled.
    pub soft_particles_enabled: bool,
    /// Soft-particle fade distance in world units.
    pub soft_particle_fade_distance: f32,
    /// Rendering statistics for the current batch.
    pub stats: BillboardBatchStats,
}

/// Statistics for a billboard batch.
#[derive(Debug, Clone, Copy, Default)]
pub struct BillboardBatchStats {
    /// Number of billboards submitted.
    pub billboard_count: u32,
    /// Number of vertices generated.
    pub vertex_count: u32,
    /// Number of indices generated.
    pub index_count: u32,
    /// Number of triangles generated.
    pub triangle_count: u32,
}

impl BillboardBatch {
    /// Create a new billboard batch.
    pub fn new() -> Self {
        Self {
            billboards: Vec::with_capacity(1024),
            vertices: Vec::with_capacity(4096),
            indices: Vec::with_capacity(6144),
            soft_particles_enabled: true,
            soft_particle_fade_distance: DEFAULT_SOFT_PARTICLE_FADE,
            stats: BillboardBatchStats::default(),
        }
    }

    /// Clear the batch for a new frame.
    pub fn clear(&mut self) {
        self.billboards.clear();
        self.vertices.clear();
        self.indices.clear();
        self.stats = BillboardBatchStats::default();
    }

    /// Submit a billboard for rendering.
    pub fn submit(&mut self, billboard: Billboard) {
        if self.billboards.len() < MAX_BILLBOARDS_PER_BATCH {
            self.billboards.push(billboard);
        }
    }

    /// Submit multiple billboards.
    pub fn submit_batch(&mut self, billboards: &[Billboard]) {
        let remaining = MAX_BILLBOARDS_PER_BATCH - self.billboards.len();
        let count = billboards.len().min(remaining);
        self.billboards.extend_from_slice(&billboards[..count]);
    }

    /// Sort billboards back-to-front and generate quad geometry.
    ///
    /// Must be called after all billboards have been submitted and before
    /// accessing vertex/index data.
    pub fn build(
        &mut self,
        camera_position: Vec3,
        camera_right: Vec3,
        camera_up: Vec3,
        camera_forward: Vec3,
        view_matrix: &Mat4,
    ) {
        // Compute sort depth for each billboard.
        for bb in &mut self.billboards {
            bb.compute_sort_depth(view_matrix);
        }

        // Sort back-to-front (furthest first for correct alpha blending).
        self.billboards.sort_by(|a, b| {
            a.sort_depth
                .partial_cmp(&b.sort_depth)
                .unwrap_or(Ordering::Equal)
        });

        // Generate quad vertices and indices.
        self.vertices.clear();
        self.indices.clear();

        for billboard in &self.billboards {
            let base_vertex = self.vertices.len() as u32;

            let (positions, uvs) = BillboardQuadBuilder::build_quad(
                billboard,
                camera_position,
                camera_right,
                camera_up,
                camera_forward,
            );

            // Emit 4 vertices for the quad.
            for i in 0..4 {
                self.vertices.push(BillboardVertex::new(
                    positions[i],
                    uvs[i],
                    billboard.color,
                    billboard.size,
                    billboard.rotation,
                ));
            }

            // Emit 6 indices (two triangles).
            self.indices.push(base_vertex);
            self.indices.push(base_vertex + 1);
            self.indices.push(base_vertex + 2);
            self.indices.push(base_vertex);
            self.indices.push(base_vertex + 2);
            self.indices.push(base_vertex + 3);
        }

        self.stats = BillboardBatchStats {
            billboard_count: self.billboards.len() as u32,
            vertex_count: self.vertices.len() as u32,
            index_count: self.indices.len() as u32,
            triangle_count: self.indices.len() as u32 / 3,
        };
    }

    /// Get the generated vertex data.
    pub fn vertices(&self) -> &[BillboardVertex] {
        &self.vertices
    }

    /// Get the generated index data.
    pub fn indices(&self) -> &[u32] {
        &self.indices
    }

    /// Get the raw vertex data as bytes for GPU upload.
    pub fn vertex_bytes(&self) -> &[u8] {
        unsafe {
            std::slice::from_raw_parts(
                self.vertices.as_ptr() as *const u8,
                self.vertices.len() * BillboardVertex::SIZE,
            )
        }
    }

    /// Get the raw index data as bytes for GPU upload.
    pub fn index_bytes(&self) -> &[u8] {
        unsafe {
            std::slice::from_raw_parts(
                self.indices.as_ptr() as *const u8,
                self.indices.len() * std::mem::size_of::<u32>(),
            )
        }
    }

    /// Get the number of submitted billboards.
    pub fn billboard_count(&self) -> usize {
        self.billboards.len()
    }

    /// Generate the WGSL fragment shader snippet for soft particles.
    pub fn soft_particle_wgsl() -> &'static str {
        SOFT_PARTICLE_WGSL
    }
}

impl Default for BillboardBatch {
    fn default() -> Self {
        Self::new()
    }
}

/// WGSL code for soft-particle depth fade.
const SOFT_PARTICLE_WGSL: &str = r#"
// Soft particle depth fade.
// Reads the scene depth buffer and fades the particle near depth intersections.
//
// Usage:
//   let fade = soft_particle_fade(frag_depth, scene_depth, fade_distance);
//   color.a *= fade;

fn soft_particle_fade(frag_depth: f32, scene_depth: f32, fade_distance: f32) -> f32 {
    let depth_diff = scene_depth - frag_depth;
    return saturate(depth_diff / max(fade_distance, 0.0001));
}
"#;

// ---------------------------------------------------------------------------
// BillboardCloud
// ---------------------------------------------------------------------------

/// Represents a complex mesh as a set of billboard planes. Each plane is a
/// textured quad positioned and oriented to approximate one face cluster of
/// the original mesh.
///
/// Billboard clouds are generated by fitting planes to the mesh geometry using
/// a greedy algorithm that selects the plane covering the most surface area
/// at each step.
#[derive(Debug, Clone)]
pub struct BillboardCloud {
    /// The billboard planes making up the cloud.
    pub planes: Vec<BillboardCloudPlane>,
}

/// A single plane in a billboard cloud.
#[derive(Debug, Clone)]
pub struct BillboardCloudPlane {
    /// Centre position of the plane in object space.
    pub center: Vec3,
    /// Normal of the plane (the direction it faces).
    pub normal: Vec3,
    /// Right axis of the plane (tangent).
    pub right: Vec3,
    /// Up axis of the plane (bitangent).
    pub up: Vec3,
    /// Half-width of the plane.
    pub half_width: f32,
    /// Half-height of the plane.
    pub half_height: f32,
    /// UV offset within the atlas for this plane's texture.
    pub uv_offset: Vec2,
    /// UV scale within the atlas for this plane's texture.
    pub uv_scale: Vec2,
}

impl BillboardCloud {
    /// Generate a billboard cloud from a mesh.
    ///
    /// Fits `num_planes` billboard planes to approximate the mesh surface.
    pub fn generate(mesh: &Mesh, num_planes: usize) -> Self {
        let num_planes = num_planes.max(1);
        let tri_count = mesh.indices.len() / 3;

        if tri_count == 0 {
            return Self { planes: Vec::new() };
        }

        // Compute per-triangle data.
        let mut tri_normals: Vec<Vec3> = Vec::with_capacity(tri_count);
        let mut tri_centroids: Vec<Vec3> = Vec::with_capacity(tri_count);
        let mut tri_areas: Vec<f32> = Vec::with_capacity(tri_count);
        let mut assigned: Vec<bool> = vec![false; tri_count];

        for t in 0..tri_count {
            let base = t * 3;
            let p0 = Vec3::from_array(mesh.vertices[mesh.indices[base] as usize].position);
            let p1 = Vec3::from_array(mesh.vertices[mesh.indices[base + 1] as usize].position);
            let p2 = Vec3::from_array(mesh.vertices[mesh.indices[base + 2] as usize].position);

            let cross = (p1 - p0).cross(p2 - p0);
            let area = cross.length() * 0.5;
            let normal = cross.normalize_or_zero();
            let centroid = (p0 + p1 + p2) / 3.0;

            tri_normals.push(normal);
            tri_centroids.push(centroid);
            tri_areas.push(area);
        }

        let mut planes = Vec::with_capacity(num_planes);

        for _ in 0..num_planes {
            // Find the unassigned triangle with the largest area.
            let mut best_tri: Option<usize> = None;
            let mut best_area: f32 = -1.0;

            for t in 0..tri_count {
                if !assigned[t] && tri_areas[t] > best_area {
                    best_area = tri_areas[t];
                    best_tri = Some(t);
                }
            }

            let seed_tri = match best_tri {
                Some(t) => t,
                None => break, // All triangles assigned.
            };

            let plane_normal = tri_normals[seed_tri];
            let plane_center = tri_centroids[seed_tri];

            // Gather all unassigned triangles close to this plane.
            let normal_threshold = 0.7; // cos(~45 degrees)
            let mut cluster_tris: Vec<usize> = Vec::new();

            for t in 0..tri_count {
                if assigned[t] {
                    continue;
                }

                let normal_dot = tri_normals[t].dot(plane_normal);
                if normal_dot < normal_threshold {
                    continue;
                }

                // Distance from triangle centroid to plane.
                let dist = (tri_centroids[t] - plane_center).dot(plane_normal).abs();
                let mesh_extent = mesh.bounds.radius();
                if dist > mesh_extent * 0.3 {
                    continue;
                }

                cluster_tris.push(t);
            }

            // Mark all cluster triangles as assigned.
            for &t in &cluster_tris {
                assigned[t] = true;
            }

            if cluster_tris.is_empty() {
                assigned[seed_tri] = true;
                continue;
            }

            // Compute the plane's tangent frame.
            let (right, up) = compute_tangent_frame(plane_normal);

            // Project all cluster vertices onto the plane to compute extents.
            let mut min_right: f32 = f32::MAX;
            let mut max_right: f32 = f32::MIN;
            let mut min_up: f32 = f32::MAX;
            let mut max_up: f32 = f32::MIN;
            let mut centroid_sum = Vec3::ZERO;
            let mut point_count = 0;

            for &t in &cluster_tris {
                let base = t * 3;
                for k in 0..3 {
                    let p = Vec3::from_array(
                        mesh.vertices[mesh.indices[base + k] as usize].position,
                    );
                    let local = p - plane_center;
                    let r = local.dot(right);
                    let u = local.dot(up);
                    min_right = min_right.min(r);
                    max_right = max_right.max(r);
                    min_up = min_up.min(u);
                    max_up = max_up.max(u);
                    centroid_sum += p;
                    point_count += 1;
                }
            }

            let center = if point_count > 0 {
                centroid_sum / point_count as f32
            } else {
                plane_center
            };

            let half_width = ((max_right - min_right) * 0.5).max(0.01);
            let half_height = ((max_up - min_up) * 0.5).max(0.01);

            planes.push(BillboardCloudPlane {
                center,
                normal: plane_normal,
                right,
                up,
                half_width,
                half_height,
                uv_offset: Vec2::ZERO,
                uv_scale: Vec2::ONE,
            });
        }

        Self { planes }
    }

    /// Convert the billboard cloud to a renderable mesh (for preview or
    /// fallback rendering).
    pub fn to_mesh(&self) -> Mesh {
        let mut builder = MeshBuilder::new();

        for plane in &self.planes {
            let hw = plane.half_width;
            let hh = plane.half_height;
            let c = plane.center;
            let r = plane.right;
            let u = plane.up;
            let n = plane.normal;

            let p0 = c - r * hw - u * hh;
            let p1 = c + r * hw - u * hh;
            let p2 = c + r * hw + u * hh;
            let p3 = c - r * hw + u * hh;

            let uv0 = plane.uv_offset;
            let uv1 = plane.uv_offset + Vec2::new(plane.uv_scale.x, 0.0);
            let uv2 = plane.uv_offset + plane.uv_scale;
            let uv3 = plane.uv_offset + Vec2::new(0.0, plane.uv_scale.y);

            let v0 = builder.add_vertex(p0, n, uv0);
            let v1 = builder.add_vertex(p1, n, uv1);
            let v2 = builder.add_vertex(p2, n, uv2);
            let v3 = builder.add_vertex(p3, n, uv3);

            builder.add_quad(v0, v1, v2, v3);
        }

        builder.build_no_tangents()
    }

    /// Number of planes in the cloud.
    pub fn plane_count(&self) -> usize {
        self.planes.len()
    }

    /// Total triangle count (2 per plane).
    pub fn triangle_count(&self) -> usize {
        self.planes.len() * 2
    }
}

/// Compute a tangent frame (right, up) for a given normal vector.
fn compute_tangent_frame(normal: Vec3) -> (Vec3, Vec3) {
    let n = normal.normalize_or_zero();
    let reference = if n.y.abs() < 0.9 { Vec3::Y } else { Vec3::X };
    let right = n.cross(reference).normalize_or_zero();
    let up = right.cross(n).normalize_or_zero();
    (right, up)
}

// ---------------------------------------------------------------------------
// Billboard WGSL shader
// ---------------------------------------------------------------------------

/// Complete WGSL vertex/fragment shader for billboard rendering.
pub const BILLBOARD_WGSL: &str = r#"
// Billboard rendering shader.
// Vertex shader expands per-instance billboard data into screen-aligned quads.
// Fragment shader applies texture, colour tint, and optional soft-particle fade.

struct BillboardInstance {
    @location(0) position: vec3<f32>,
    @location(1) size: vec2<f32>,
    @location(2) color: vec4<f32>,
    @location(3) uv_rect: vec4<f32>,
    @location(4) rotation: f32,
}

struct CameraUniforms {
    view: mat4x4<f32>,
    projection: mat4x4<f32>,
    view_projection: mat4x4<f32>,
    camera_position: vec3<f32>,
    camera_right: vec3<f32>,
    camera_up: vec3<f32>,
    viewport_size: vec2<f32>,
}

@group(0) @binding(0) var<uniform> camera: CameraUniforms;
@group(1) @binding(0) var billboard_texture: texture_2d<f32>;
@group(1) @binding(1) var billboard_sampler: sampler;

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) uv: vec2<f32>,
    @location(1) color: vec4<f32>,
}

// Quad corner offsets: BL, BR, TR, TL.
const QUAD_OFFSETS: array<vec2<f32>, 4> = array<vec2<f32>, 4>(
    vec2<f32>(-1.0, -1.0),
    vec2<f32>( 1.0, -1.0),
    vec2<f32>( 1.0,  1.0),
    vec2<f32>(-1.0,  1.0)
);

const QUAD_UVS: array<vec2<f32>, 4> = array<vec2<f32>, 4>(
    vec2<f32>(0.0, 1.0),
    vec2<f32>(1.0, 1.0),
    vec2<f32>(1.0, 0.0),
    vec2<f32>(0.0, 0.0)
);

@vertex
fn vs_main(
    instance: BillboardInstance,
    @builtin(vertex_index) vertex_index: u32,
) -> VertexOutput {
    var output: VertexOutput;

    let corner = QUAD_OFFSETS[vertex_index % 4u];
    let base_uv = QUAD_UVS[vertex_index % 4u];

    // Apply rotation.
    let cos_r = cos(instance.rotation);
    let sin_r = sin(instance.rotation);
    let rotated = vec2<f32>(
        corner.x * cos_r - corner.y * sin_r,
        corner.x * sin_r + corner.y * cos_r
    );

    // Expand to world-space offset.
    let right = camera.camera_right * rotated.x * instance.size.x;
    let up = camera.camera_up * rotated.y * instance.size.y;
    let world_pos = instance.position + right + up;

    output.clip_position = camera.view_projection * vec4<f32>(world_pos, 1.0);

    // Map base UV to atlas UV rect.
    output.uv = mix(
        instance.uv_rect.xy,
        instance.uv_rect.zw,
        base_uv
    );

    output.color = instance.color;

    return output;
}

@fragment
fn fs_main(input: VertexOutput) -> @location(0) vec4<f32> {
    let tex_color = textureSample(billboard_texture, billboard_sampler, input.uv);
    let final_color = tex_color * input.color;

    // Alpha test: discard near-transparent fragments.
    if (final_color.a < 0.01) {
        discard;
    }

    return final_color;
}
"#;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh::create_sphere;

    #[test]
    fn test_billboard_default() {
        let bb = Billboard::default();
        assert_eq!(bb.position, Vec3::ZERO);
        assert_eq!(bb.size, Vec2::splat(1.0));
        assert_eq!(bb.rotation, 0.0);
    }

    #[test]
    fn test_billboard_builder() {
        let bb = Billboard::new(Vec3::ONE, Vec2::new(2.0, 3.0), 42)
            .with_facing(BillboardFacingMode::WorldY)
            .with_color(Vec4::new(1.0, 0.0, 0.0, 1.0))
            .with_rotation(1.57);

        assert_eq!(bb.position, Vec3::ONE);
        assert_eq!(bb.texture_handle, 42);
        assert!(matches!(bb.facing_mode, BillboardFacingMode::WorldY));
        assert!((bb.rotation - 1.57).abs() < 1e-5);
    }

    #[test]
    fn test_billboard_sort_depth() {
        let view = Mat4::look_at_rh(Vec3::new(0.0, 0.0, 5.0), Vec3::ZERO, Vec3::Y);

        let mut bb1 = Billboard::new(Vec3::new(0.0, 0.0, 0.0), Vec2::ONE, 0);
        let mut bb2 = Billboard::new(Vec3::new(0.0, 0.0, 3.0), Vec2::ONE, 0);

        bb1.compute_sort_depth(&view);
        bb2.compute_sort_depth(&view);

        // bb1 is at z=0, bb2 is at z=3. In view space, bb1 should be further
        // (more negative z) than bb2.
        assert!(bb1.sort_depth < bb2.sort_depth);
    }

    #[test]
    fn test_quad_generation_screen_aligned() {
        let bb = Billboard::new(Vec3::ZERO, Vec2::splat(1.0), 0);
        let (positions, uvs) = BillboardQuadBuilder::build_quad(
            &bb,
            Vec3::new(0.0, 0.0, 5.0),
            Vec3::X,
            Vec3::Y,
            -Vec3::Z,
        );

        // All 4 corners should be at z=0 (billboard plane).
        for p in &positions {
            assert!((p.z - 0.0).abs() < 1e-5);
        }

        // Width should span from -1 to +1 on X.
        assert!((positions[0].x - (-1.0)).abs() < 1e-5); // bottom-left
        assert!((positions[1].x - 1.0).abs() < 1e-5);    // bottom-right
    }

    #[test]
    fn test_quad_generation_world_y() {
        let bb = Billboard::new(Vec3::ZERO, Vec2::splat(1.0), 0)
            .with_facing(BillboardFacingMode::WorldY);

        let (positions, _) = BillboardQuadBuilder::build_quad(
            &bb,
            Vec3::new(5.0, 0.0, 0.0),
            Vec3::Z,
            Vec3::Y,
            -Vec3::X,
        );

        // All Y values should use the world Y axis.
        // Top corners should be at y=1, bottom at y=-1.
        assert!((positions[2].y - 1.0).abs() < 1e-5);
        assert!((positions[0].y - (-1.0)).abs() < 1e-5);
    }

    #[test]
    fn test_quad_generation_velocity() {
        let bb = Billboard::new(Vec3::ZERO, Vec2::splat(1.0), 0)
            .with_facing(BillboardFacingMode::Velocity)
            .with_velocity(Vec3::new(0.0, 5.0, 0.0));

        let (positions, _) = BillboardQuadBuilder::build_quad(
            &bb,
            Vec3::new(0.0, 0.0, 5.0),
            Vec3::X,
            Vec3::Y,
            -Vec3::Z,
        );

        // The quad should be stretched along Y (velocity direction).
        let height = (positions[2].y - positions[0].y).abs();
        assert!(height > 0.0);
    }

    #[test]
    fn test_atlas_allocation() {
        let mut atlas = BillboardAtlas::new(4, 256, 2);
        assert_eq!(atlas.total_tile_count(), 16);
        assert_eq!(atlas.free_tile_count(), 16);

        let tile = atlas.allocate_tile(100);
        assert_eq!(tile, Some(0));
        assert_eq!(atlas.free_tile_count(), 15);

        // Re-allocating the same type should return the same tile.
        let tile2 = atlas.allocate_tile(100);
        assert_eq!(tile2, Some(0));
        assert_eq!(atlas.free_tile_count(), 15);
    }

    #[test]
    fn test_atlas_uv_rect() {
        let atlas = BillboardAtlas::new(4, 256, 0);
        let uv = atlas.tile_uv_rect(0);
        assert!((uv.x - 0.0).abs() < 1e-5);
        assert!((uv.y - 0.0).abs() < 1e-5);
        assert!((uv.z - 0.25).abs() < 1e-5);
        assert!((uv.w - 0.25).abs() < 1e-5);

        let uv5 = atlas.tile_uv_rect(5); // col=1, row=1
        assert!((uv5.x - 0.25).abs() < 1e-5);
        assert!((uv5.y - 0.25).abs() < 1e-5);
    }

    #[test]
    fn test_atlas_pixel_rect() {
        let atlas = BillboardAtlas::new(4, 128, 4);
        let (x, y, w, h) = atlas.tile_pixel_rect(0);
        assert_eq!(x, 0);
        assert_eq!(y, 0);
        assert_eq!(w, 128);
        assert_eq!(h, 128);

        let (x1, y1, _, _) = atlas.tile_pixel_rect(1);
        assert_eq!(x1, 132); // 128 + 4 padding
        assert_eq!(y1, 0);
    }

    #[test]
    fn test_impostor_select_angle() {
        let impostor = ImpostorRenderer::new_horizontal(8);
        assert_eq!(impostor.total_angles(), 8);

        // Looking from the front (+Z direction) should select the angle
        // whose view direction is closest to +Z.
        let angle = impostor.select_angle(Vec3::Z);
        let dir = impostor.view_directions[angle];
        assert!(dir.z > 0.5, "Expected front-facing angle, got {dir:?}");
    }

    #[test]
    fn test_impostor_blended_angle() {
        let impostor = ImpostorRenderer::new_horizontal(8);
        let (best, second, factor) = impostor.select_angle_blended(Vec3::X);

        // Best and second should be different angles.
        assert_ne!(best, second);
        assert!(factor >= 0.0 && factor <= 1.0);
    }

    #[test]
    fn test_octahedral_roundtrip() {
        let test_dirs = [
            Vec3::X,
            Vec3::Y,
            Vec3::Z,
            -Vec3::X,
            -Vec3::Y,
            -Vec3::Z,
            Vec3::new(1.0, 1.0, 1.0).normalize(),
            Vec3::new(-1.0, 0.5, 0.7).normalize(),
        ];

        for dir in &test_dirs {
            let encoded = OctahedralMapping::encode(*dir);
            assert!(encoded.x >= 0.0 && encoded.x <= 1.0, "U out of range");
            assert!(encoded.y >= 0.0 && encoded.y <= 1.0, "V out of range");

            let decoded = OctahedralMapping::decode(encoded);
            let error = (*dir - decoded).length();
            assert!(
                error < 0.01,
                "Octahedral roundtrip error {error} for {dir:?} -> {encoded:?} -> {decoded:?}"
            );
        }
    }

    #[test]
    fn test_billboard_batch_build() {
        let mut batch = BillboardBatch::new();

        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -5.0), Vec2::ONE, 0));
        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -10.0), Vec2::ONE, 0));
        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -2.0), Vec2::ONE, 0));

        let view = Mat4::look_at_rh(Vec3::ZERO, -Vec3::Z, Vec3::Y);

        batch.build(
            Vec3::ZERO,
            Vec3::X,
            Vec3::Y,
            -Vec3::Z,
            &view,
        );

        assert_eq!(batch.stats.billboard_count, 3);
        assert_eq!(batch.stats.vertex_count, 12); // 3 * 4
        assert_eq!(batch.stats.index_count, 18);  // 3 * 6
        assert_eq!(batch.stats.triangle_count, 6); // 3 * 2
    }

    #[test]
    fn test_billboard_batch_sorting() {
        let mut batch = BillboardBatch::new();

        // Submit billboards out of depth order.
        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -2.0), Vec2::ONE, 0));
        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -10.0), Vec2::ONE, 0));
        batch.submit(Billboard::new(Vec3::new(0.0, 0.0, -5.0), Vec2::ONE, 0));

        let view = Mat4::look_at_rh(Vec3::ZERO, -Vec3::Z, Vec3::Y);

        batch.build(Vec3::ZERO, Vec3::X, Vec3::Y, -Vec3::Z, &view);

        // After sorting, the billboard at z=-10 should come first (back-to-front).
        // The first 4 vertices should correspond to the furthest billboard.
        let first_pos = Vec3::from_array(batch.vertices()[0].position);
        // Furthest billboard is at z=-10, so its vertices should have z ~ -10.
        assert!(
            first_pos.z < -8.0,
            "Expected furthest billboard first, got z={}", first_pos.z
        );
    }

    #[test]
    fn test_billboard_batch_clear() {
        let mut batch = BillboardBatch::new();
        batch.submit(Billboard::default());
        assert_eq!(batch.billboard_count(), 1);

        batch.clear();
        assert_eq!(batch.billboard_count(), 0);
        assert_eq!(batch.stats.billboard_count, 0);
    }

    #[test]
    fn test_billboard_cloud_generation() {
        let mesh = create_sphere(8, 6);
        let cloud = BillboardCloud::generate(&mesh, 6);

        assert!(cloud.plane_count() > 0);
        assert!(cloud.plane_count() <= 6);
        assert_eq!(cloud.triangle_count(), cloud.plane_count() * 2);
    }

    #[test]
    fn test_billboard_cloud_to_mesh() {
        let mesh = create_sphere(8, 6);
        let cloud = BillboardCloud::generate(&mesh, 4);
        let cloud_mesh = cloud.to_mesh();

        assert_eq!(cloud_mesh.triangle_count(), cloud.plane_count() as u32 * 2);
        assert!(cloud_mesh.vertex_count > 0);
    }

    #[test]
    fn test_billboard_cloud_empty_mesh() {
        let mesh = Mesh::new(Vec::new(), Vec::new());
        let cloud = BillboardCloud::generate(&mesh, 4);
        assert_eq!(cloud.plane_count(), 0);
    }

    #[test]
    fn test_compute_tangent_frame() {
        let (right, up) = compute_tangent_frame(Vec3::Y);
        // Right and up should be perpendicular to Y and to each other.
        assert!(right.dot(Vec3::Y).abs() < 1e-5);
        assert!(up.dot(Vec3::Y).abs() < 1e-5);
        assert!(right.dot(up).abs() < 1e-5);
        // All should be unit length.
        assert!((right.length() - 1.0).abs() < 1e-5);
        assert!((up.length() - 1.0).abs() < 1e-5);
    }

    #[test]
    fn test_billboard_vertex_size() {
        // Ensure the vertex struct has a known size for GPU layout.
        assert!(BillboardVertex::SIZE > 0);
        assert_eq!(BillboardVertex::SIZE, std::mem::size_of::<BillboardVertex>());
    }

    #[test]
    fn test_impostor_renderer_creation() {
        let imp = ImpostorRenderer::new(8, 4);
        assert_eq!(imp.total_angles(), 32);
        assert_eq!(imp.view_directions.len(), 32);

        // All view directions should be unit vectors.
        for dir in &imp.view_directions {
            assert!(
                (dir.length() - 1.0).abs() < 1e-4,
                "Non-unit view direction: {dir:?}"
            );
        }
    }

    #[test]
    fn test_impostor_tile_set_get() {
        let mut imp = ImpostorRenderer::new_horizontal(8);
        imp.set_tile(3, 42);
        assert_eq!(imp.get_tile(3), 42);
        assert_eq!(imp.get_tile(0), 0); // default
    }

    #[test]
    fn test_atlas_full() {
        let mut atlas = BillboardAtlas::new(2, 64, 0);
        // 2x2 = 4 tiles.
        for i in 0..4 {
            assert!(atlas.allocate_tile(i).is_some());
        }
        // 5th should fail.
        assert!(atlas.allocate_tile(99).is_none());
        assert_eq!(atlas.free_tile_count(), 0);
    }

    #[test]
    fn test_billboard_batch_bytes() {
        let mut batch = BillboardBatch::new();
        batch.submit(Billboard::new(Vec3::ZERO, Vec2::ONE, 0));

        let view = Mat4::IDENTITY;
        batch.build(Vec3::ZERO, Vec3::X, Vec3::Y, -Vec3::Z, &view);

        let vb = batch.vertex_bytes();
        assert_eq!(vb.len(), 4 * BillboardVertex::SIZE);

        let ib = batch.index_bytes();
        assert_eq!(ib.len(), 6 * std::mem::size_of::<u32>());
    }
}
