// engine/render/src/render_profiler.rs
//
// GPU render profiler for the Genovo engine.
//
// Provides detailed GPU performance analysis through timestamp queries,
// pipeline statistics, and frame graph timeline construction.
//
// Features:
// - Per-pass timestamp queries for GPU timing.
// - Pipeline statistics queries (vertex/fragment invocations, primitives).
// - Frame graph timeline visualization data.
// - Bottleneck detection based on pass durations and resource usage.
// - Multi-frame averaging and spike detection.
// - Hierarchical scope tree for nested GPU operations.
// - Export to Chrome Trace format for external analysis.

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum number of timestamp query pairs per frame.
const MAX_TIMESTAMP_QUERIES: usize = 256;

/// Number of frames to average for statistics.
const AVERAGING_WINDOW: usize = 60;

/// Threshold factor for spike detection (N times average).
const SPIKE_THRESHOLD_FACTOR: f32 = 2.0;

/// Minimum duration to be considered a bottleneck (in microseconds).
const BOTTLENECK_THRESHOLD_US: f64 = 500.0;

// ---------------------------------------------------------------------------
// GPU Timestamp
// ---------------------------------------------------------------------------

/// A pair of GPU timestamps marking the start and end of a scope.
#[derive(Debug, Clone)]
pub struct GpuTimestamp {
    /// Scope name.
    pub name: String,
    /// Start timestamp (in GPU ticks).
    pub start_ticks: u64,
    /// End timestamp (in GPU ticks).
    pub end_ticks: u64,
    /// Duration in microseconds (computed after resolving timestamps).
    pub duration_us: f64,
    /// Parent scope index (-1 for root).
    pub parent_index: i32,
    /// Depth in the scope hierarchy.
    pub depth: u32,
    /// Color for visualization (RGBA).
    pub color: [f32; 4],
}

impl GpuTimestamp {
    /// Create a new unresolved timestamp scope.
    pub fn new(name: &str, depth: u32, parent: i32) -> Self {
        Self {
            name: name.to_string(),
            start_ticks: 0,
            end_ticks: 0,
            duration_us: 0.0,
            parent_index: parent,
            depth,
            color: Self::color_for_name(name),
        }
    }

    /// Resolve the timestamp ticks to microseconds given the GPU frequency.
    pub fn resolve(&mut self, gpu_frequency: f64) {
        if gpu_frequency > 0.0 && self.end_ticks >= self.start_ticks {
            let ticks = (self.end_ticks - self.start_ticks) as f64;
            self.duration_us = ticks / gpu_frequency * 1_000_000.0;
        }
    }

    /// Generate a deterministic color from the scope name.
    fn color_for_name(name: &str) -> [f32; 4] {
        let mut hash: u32 = 5381;
        for b in name.bytes() {
            hash = hash.wrapping_mul(33).wrapping_add(b as u32);
        }

        let r = ((hash >> 16) & 0xFF) as f32 / 255.0 * 0.5 + 0.3;
        let g = ((hash >> 8) & 0xFF) as f32 / 255.0 * 0.5 + 0.3;
        let b = (hash & 0xFF) as f32 / 255.0 * 0.5 + 0.3;
        [r, g, b, 1.0]
    }
}

// ---------------------------------------------------------------------------
// Pipeline Statistics
// ---------------------------------------------------------------------------

/// GPU pipeline statistics from a query.
#[derive(Debug, Clone, Default)]
pub struct PipelineStats {
    /// Number of vertices submitted to the input assembler.
    pub vertices_submitted: u64,
    /// Number of primitives submitted.
    pub primitives_submitted: u64,
    /// Number of vertex shader invocations.
    pub vertex_shader_invocations: u64,
    /// Number of geometry shader invocations.
    pub geometry_shader_invocations: u64,
    /// Number of primitives generated by the geometry shader.
    pub geometry_shader_primitives: u64,
    /// Number of fragment shader invocations.
    pub fragment_shader_invocations: u64,
    /// Number of compute shader invocations.
    pub compute_shader_invocations: u64,
    /// Number of primitives that passed clipping.
    pub clipping_primitives: u64,
    /// Number of tessellation control shader invocations.
    pub tess_control_invocations: u64,
    /// Number of tessellation evaluation shader invocations.
    pub tess_eval_invocations: u64,
}

impl PipelineStats {
    /// Compute the vertex-to-fragment ratio.
    pub fn vertex_fragment_ratio(&self) -> f64 {
        if self.fragment_shader_invocations == 0 {
            return 0.0;
        }
        self.vertex_shader_invocations as f64 / self.fragment_shader_invocations as f64
    }

    /// Estimate overdraw (fragment invocations / pixels rendered).
    pub fn estimated_overdraw(&self, viewport_pixels: u64) -> f64 {
        if viewport_pixels == 0 {
            return 0.0;
        }
        self.fragment_shader_invocations as f64 / viewport_pixels as f64
    }

    /// Total shader invocations across all stages.
    pub fn total_invocations(&self) -> u64 {
        self.vertex_shader_invocations
            + self.geometry_shader_invocations
            + self.fragment_shader_invocations
            + self.compute_shader_invocations
            + self.tess_control_invocations
            + self.tess_eval_invocations
    }
}

// ---------------------------------------------------------------------------
// Pass Profile
// ---------------------------------------------------------------------------

/// Profile data for a single render pass.
#[derive(Debug, Clone)]
pub struct PassProfile {
    /// Pass name.
    pub name: String,
    /// GPU duration in microseconds.
    pub gpu_time_us: f64,
    /// CPU time spent recording commands for this pass (microseconds).
    pub cpu_time_us: f64,
    /// Pipeline statistics for this pass.
    pub pipeline_stats: PipelineStats,
    /// Number of draw calls in this pass.
    pub draw_calls: u32,
    /// Number of dispatches (compute) in this pass.
    pub dispatches: u32,
    /// Render target resolution (width, height).
    pub resolution: (u32, u32),
    /// Number of render targets written.
    pub render_target_count: u32,
    /// Whether this is a compute pass.
    pub is_compute: bool,
    /// Memory bandwidth estimate in MB/s.
    pub bandwidth_estimate_mb: f64,
    /// Pass category for grouping.
    pub category: PassCategory,
}

/// Category for render pass grouping.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PassCategory {
    /// Geometry rendering (G-buffer, forward).
    Geometry,
    /// Shadow map rendering.
    Shadow,
    /// Lighting computation.
    Lighting,
    /// Post-processing effects.
    PostProcess,
    /// UI rendering.
    Ui,
    /// Compute passes.
    Compute,
    /// Debug visualization.
    Debug,
    /// Transfer/copy operations.
    Transfer,
    /// Other / uncategorized.
    Other,
}

impl PassProfile {
    /// Create a new pass profile.
    pub fn new(name: &str, category: PassCategory) -> Self {
        Self {
            name: name.to_string(),
            gpu_time_us: 0.0,
            cpu_time_us: 0.0,
            pipeline_stats: PipelineStats::default(),
            draw_calls: 0,
            dispatches: 0,
            resolution: (0, 0),
            render_target_count: 0,
            is_compute: false,
            bandwidth_estimate_mb: 0.0,
            category,
        }
    }

    /// Returns the pass duration in milliseconds.
    pub fn gpu_time_ms(&self) -> f64 {
        self.gpu_time_us / 1000.0
    }

    /// Returns the CPU time in milliseconds.
    pub fn cpu_time_ms(&self) -> f64 {
        self.cpu_time_us / 1000.0
    }
}

// ---------------------------------------------------------------------------
// Bottleneck Detection
// ---------------------------------------------------------------------------

/// Identified bottleneck in the render pipeline.
#[derive(Debug, Clone)]
pub struct Bottleneck {
    /// Name of the bottleneck pass or scope.
    pub name: String,
    /// Duration in microseconds.
    pub duration_us: f64,
    /// Percentage of total frame time.
    pub percentage: f64,
    /// Type of bottleneck.
    pub bottleneck_type: BottleneckType,
    /// Suggested mitigation.
    pub suggestion: String,
}

/// Type of rendering bottleneck.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BottleneckType {
    /// GPU vertex processing bound.
    VertexBound,
    /// GPU fragment processing bound.
    FragmentBound,
    /// GPU compute bound.
    ComputeBound,
    /// GPU bandwidth bound.
    BandwidthBound,
    /// CPU command recording bound.
    CpuBound,
    /// Excessive overdraw.
    Overdraw,
    /// Too many draw calls.
    DrawCallBound,
    /// General long-running pass.
    LongPass,
}

/// Detect bottlenecks in a frame's pass profiles.
pub fn detect_bottlenecks(passes: &[PassProfile], total_frame_us: f64) -> Vec<Bottleneck> {
    let mut bottlenecks = Vec::new();

    for pass in passes {
        if pass.gpu_time_us < BOTTLENECK_THRESHOLD_US {
            continue;
        }

        let percentage = if total_frame_us > 0.0 {
            pass.gpu_time_us / total_frame_us * 100.0
        } else {
            0.0
        };

        // Check for excessive draw calls.
        if pass.draw_calls > 1000 {
            bottlenecks.push(Bottleneck {
                name: pass.name.clone(),
                duration_us: pass.gpu_time_us,
                percentage,
                bottleneck_type: BottleneckType::DrawCallBound,
                suggestion: format!(
                    "Reduce draw calls in '{}' (currently {}). Consider instancing or batching.",
                    pass.name, pass.draw_calls
                ),
            });
        }

        // Check for overdraw.
        let viewport_pixels = pass.resolution.0 as u64 * pass.resolution.1 as u64;
        let overdraw = pass.pipeline_stats.estimated_overdraw(viewport_pixels);
        if overdraw > 3.0 {
            bottlenecks.push(Bottleneck {
                name: pass.name.clone(),
                duration_us: pass.gpu_time_us,
                percentage,
                bottleneck_type: BottleneckType::Overdraw,
                suggestion: format!(
                    "High overdraw ({:.1}x) in '{}'. Consider better sorting or occlusion culling.",
                    overdraw, pass.name
                ),
            });
        }

        // Check for fragment-bound passes.
        if pass.pipeline_stats.fragment_shader_invocations > 0
            && pass.pipeline_stats.vertex_fragment_ratio() < 0.001
            && percentage > 15.0
        {
            bottlenecks.push(Bottleneck {
                name: pass.name.clone(),
                duration_us: pass.gpu_time_us,
                percentage,
                bottleneck_type: BottleneckType::FragmentBound,
                suggestion: format!(
                    "Pass '{}' appears fragment-bound ({:.1}% of frame). Consider reducing shader complexity or resolution.",
                    pass.name, percentage
                ),
            });
        }

        // Long pass detection.
        if percentage > 25.0 {
            bottlenecks.push(Bottleneck {
                name: pass.name.clone(),
                duration_us: pass.gpu_time_us,
                percentage,
                bottleneck_type: BottleneckType::LongPass,
                suggestion: format!(
                    "Pass '{}' takes {:.1}% of frame ({:.2}ms). Consider splitting or optimising.",
                    pass.name, percentage, pass.gpu_time_us / 1000.0
                ),
            });
        }
    }

    bottlenecks.sort_by(|a, b| b.duration_us.partial_cmp(&a.duration_us).unwrap_or(std::cmp::Ordering::Equal));
    bottlenecks
}

// ---------------------------------------------------------------------------
// Frame Profile
// ---------------------------------------------------------------------------

/// Complete profile data for a single rendered frame.
#[derive(Debug, Clone)]
pub struct RenderFrameProfile {
    /// Frame number.
    pub frame_number: u64,
    /// Total GPU time in microseconds.
    pub total_gpu_us: f64,
    /// Total CPU time in microseconds.
    pub total_cpu_us: f64,
    /// Per-pass profiles.
    pub passes: Vec<PassProfile>,
    /// Timestamp scopes (hierarchical).
    pub timestamps: Vec<GpuTimestamp>,
    /// Detected bottlenecks.
    pub bottlenecks: Vec<Bottleneck>,
    /// Aggregate pipeline statistics.
    pub total_stats: PipelineStats,
    /// Total draw calls across all passes.
    pub total_draw_calls: u32,
    /// Total dispatches across all passes.
    pub total_dispatches: u32,
}

impl RenderFrameProfile {
    /// Create a new frame profile.
    pub fn new(frame_number: u64) -> Self {
        Self {
            frame_number,
            total_gpu_us: 0.0,
            total_cpu_us: 0.0,
            passes: Vec::new(),
            timestamps: Vec::new(),
            bottlenecks: Vec::new(),
            total_stats: PipelineStats::default(),
            total_draw_calls: 0,
            total_dispatches: 0,
        }
    }

    /// Compute totals from individual passes.
    pub fn finalize(&mut self) {
        self.total_gpu_us = self.passes.iter().map(|p| p.gpu_time_us).sum();
        self.total_cpu_us = self.passes.iter().map(|p| p.cpu_time_us).sum();
        self.total_draw_calls = self.passes.iter().map(|p| p.draw_calls).sum();
        self.total_dispatches = self.passes.iter().map(|p| p.dispatches).sum();

        for pass in &self.passes {
            self.total_stats.vertices_submitted += pass.pipeline_stats.vertices_submitted;
            self.total_stats.primitives_submitted += pass.pipeline_stats.primitives_submitted;
            self.total_stats.vertex_shader_invocations += pass.pipeline_stats.vertex_shader_invocations;
            self.total_stats.fragment_shader_invocations += pass.pipeline_stats.fragment_shader_invocations;
            self.total_stats.compute_shader_invocations += pass.pipeline_stats.compute_shader_invocations;
        }

        self.bottlenecks = detect_bottlenecks(&self.passes, self.total_gpu_us);
    }

    /// Returns total GPU time in milliseconds.
    pub fn total_gpu_ms(&self) -> f64 {
        self.total_gpu_us / 1000.0
    }

    /// Returns total CPU time in milliseconds.
    pub fn total_cpu_ms(&self) -> f64 {
        self.total_cpu_us / 1000.0
    }

    /// Get time breakdown by pass category.
    pub fn time_by_category(&self) -> HashMap<PassCategory, f64> {
        let mut result = HashMap::new();
        for pass in &self.passes {
            *result.entry(pass.category).or_insert(0.0) += pass.gpu_time_us;
        }
        result
    }
}

// ---------------------------------------------------------------------------
// Render Profiler
// ---------------------------------------------------------------------------

/// Main render profiler that collects and analyses GPU timing data.
#[derive(Debug)]
pub struct RenderProfiler {
    /// Whether profiling is enabled.
    pub enabled: bool,
    /// Current frame being profiled.
    pub current_frame: RenderFrameProfile,
    /// History of recent frame profiles.
    pub history: Vec<RenderFrameProfile>,
    /// Maximum history length.
    pub max_history: usize,
    /// GPU timestamp frequency (ticks per second).
    pub gpu_frequency: f64,
    /// Current scope stack for hierarchical timing.
    scope_stack: Vec<usize>,
    /// Frame number counter.
    frame_counter: u64,
    /// Per-pass running averages.
    pub pass_averages: HashMap<String, RunningAverage>,
    /// Spike detection threshold factor.
    pub spike_threshold: f32,
    /// Whether to detect bottlenecks.
    pub detect_bottlenecks: bool,
}

impl RenderProfiler {
    /// Create a new render profiler.
    pub fn new() -> Self {
        Self {
            enabled: false,
            current_frame: RenderFrameProfile::new(0),
            history: Vec::new(),
            max_history: AVERAGING_WINDOW,
            gpu_frequency: 1_000_000_000.0,
            scope_stack: Vec::new(),
            frame_counter: 0,
            pass_averages: HashMap::new(),
            spike_threshold: SPIKE_THRESHOLD_FACTOR,
            detect_bottlenecks: true,
        }
    }

    /// Enable or disable profiling.
    pub fn set_enabled(&mut self, enabled: bool) {
        self.enabled = enabled;
    }

    /// Set the GPU timestamp frequency.
    pub fn set_gpu_frequency(&mut self, frequency: f64) {
        self.gpu_frequency = frequency;
    }

    /// Begin a new frame profile.
    pub fn begin_frame(&mut self) {
        if !self.enabled {
            return;
        }
        self.frame_counter += 1;
        self.current_frame = RenderFrameProfile::new(self.frame_counter);
        self.scope_stack.clear();
    }

    /// Begin a timing scope.
    pub fn begin_scope(&mut self, name: &str) -> usize {
        if !self.enabled {
            return 0;
        }

        let parent = self.scope_stack.last().map(|&i| i as i32).unwrap_or(-1);
        let depth = self.scope_stack.len() as u32;
        let index = self.current_frame.timestamps.len();

        self.current_frame.timestamps.push(GpuTimestamp::new(name, depth, parent));
        self.scope_stack.push(index);

        index
    }

    /// End the current timing scope.
    pub fn end_scope(&mut self) {
        if !self.enabled {
            return;
        }
        self.scope_stack.pop();
    }

    /// Add a pass profile to the current frame.
    pub fn add_pass(&mut self, profile: PassProfile) {
        if !self.enabled {
            return;
        }
        self.current_frame.passes.push(profile);
    }

    /// End the current frame and finalize statistics.
    pub fn end_frame(&mut self) {
        if !self.enabled {
            return;
        }

        // Resolve timestamps.
        for timestamp in &mut self.current_frame.timestamps {
            timestamp.resolve(self.gpu_frequency);
        }

        self.current_frame.finalize();

        // Update running averages.
        for pass in &self.current_frame.passes {
            let avg = self.pass_averages
                .entry(pass.name.clone())
                .or_insert_with(|| RunningAverage::new(self.max_history));
            avg.add_sample(pass.gpu_time_us);
        }

        // Store in history.
        let frame = self.current_frame.clone();
        self.history.push(frame);
        if self.history.len() > self.max_history {
            self.history.remove(0);
        }
    }

    /// Get the average GPU time for a specific pass.
    pub fn pass_average(&self, name: &str) -> f64 {
        self.pass_averages.get(name).map(|a| a.average()).unwrap_or(0.0)
    }

    /// Get the maximum GPU time for a specific pass in recent history.
    pub fn pass_max(&self, name: &str) -> f64 {
        self.pass_averages.get(name).map(|a| a.max()).unwrap_or(0.0)
    }

    /// Detect timing spikes for a pass.
    pub fn is_spike(&self, name: &str, current_value: f64) -> bool {
        if let Some(avg) = self.pass_averages.get(name) {
            let threshold = avg.average() * self.spike_threshold as f64;
            current_value > threshold && threshold > 0.0
        } else {
            false
        }
    }

    /// Get the overall frame time average in milliseconds.
    pub fn average_frame_time_ms(&self) -> f64 {
        if self.history.is_empty() {
            return 0.0;
        }
        let sum: f64 = self.history.iter().map(|f| f.total_gpu_us).sum();
        sum / self.history.len() as f64 / 1000.0
    }

    /// Get the 99th percentile frame time in milliseconds.
    pub fn percentile_99_frame_time_ms(&self) -> f64 {
        if self.history.is_empty() {
            return 0.0;
        }
        let mut times: Vec<f64> = self.history.iter().map(|f| f.total_gpu_us).collect();
        times.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        let idx = (times.len() as f64 * 0.99).ceil() as usize - 1;
        times[idx.min(times.len() - 1)] / 1000.0
    }

    /// Generate a timeline for Chrome Trace format (JSON).
    pub fn export_chrome_trace(&self) -> String {
        let mut events = Vec::new();

        for frame in &self.history {
            for timestamp in &frame.timestamps {
                events.push(format!(
                    r#"{{"name":"{}","ph":"X","ts":{:.0},"dur":{:.0},"pid":1,"tid":{}}}"#,
                    timestamp.name,
                    timestamp.start_ticks as f64 / self.gpu_frequency * 1_000_000.0,
                    timestamp.duration_us,
                    timestamp.depth
                ));
            }
        }

        format!("[{}]", events.join(","))
    }

    /// Get a summary string of the current frame performance.
    pub fn summary(&self) -> String {
        let frame = &self.current_frame;
        let mut summary = format!(
            "Frame {}: GPU {:.2}ms, CPU {:.2}ms, {} draws, {} dispatches\n",
            frame.frame_number,
            frame.total_gpu_ms(),
            frame.total_cpu_ms(),
            frame.total_draw_calls,
            frame.total_dispatches,
        );

        for pass in &frame.passes {
            summary.push_str(&format!(
                "  {}: {:.2}ms ({} draws)\n",
                pass.name,
                pass.gpu_time_ms(),
                pass.draw_calls,
            ));
        }

        if !frame.bottlenecks.is_empty() {
            summary.push_str("Bottlenecks:\n");
            for bottleneck in &frame.bottlenecks {
                summary.push_str(&format!("  {}\n", bottleneck.suggestion));
            }
        }

        summary
    }
}

// ---------------------------------------------------------------------------
// Running Average
// ---------------------------------------------------------------------------

/// Windowed running average for a sampled metric.
#[derive(Debug, Clone)]
pub struct RunningAverage {
    /// Sample buffer.
    pub samples: Vec<f64>,
    /// Current write position.
    pub write_pos: usize,
    /// Number of samples collected.
    pub count: usize,
    /// Window size.
    pub window_size: usize,
}

impl RunningAverage {
    /// Create a new running average with the given window size.
    pub fn new(window_size: usize) -> Self {
        Self {
            samples: vec![0.0; window_size],
            write_pos: 0,
            count: 0,
            window_size,
        }
    }

    /// Add a sample.
    pub fn add_sample(&mut self, value: f64) {
        self.samples[self.write_pos] = value;
        self.write_pos = (self.write_pos + 1) % self.window_size;
        if self.count < self.window_size {
            self.count += 1;
        }
    }

    /// Compute the average of all samples.
    pub fn average(&self) -> f64 {
        if self.count == 0 {
            return 0.0;
        }
        let sum: f64 = self.samples[..self.count].iter().sum();
        sum / self.count as f64
    }

    /// Get the maximum sample value.
    pub fn max(&self) -> f64 {
        if self.count == 0 {
            return 0.0;
        }
        self.samples[..self.count]
            .iter()
            .copied()
            .fold(f64::MIN, f64::max)
    }

    /// Get the minimum sample value.
    pub fn min(&self) -> f64 {
        if self.count == 0 {
            return 0.0;
        }
        self.samples[..self.count]
            .iter()
            .copied()
            .fold(f64::MAX, f64::min)
    }

    /// Get the standard deviation.
    pub fn std_dev(&self) -> f64 {
        if self.count < 2 {
            return 0.0;
        }
        let avg = self.average();
        let variance: f64 = self.samples[..self.count]
            .iter()
            .map(|&v| (v - avg) * (v - avg))
            .sum::<f64>()
            / (self.count - 1) as f64;
        variance.sqrt()
    }

    /// Get the last N samples.
    pub fn last_n(&self, n: usize) -> Vec<f64> {
        let n = n.min(self.count);
        let mut result = Vec::with_capacity(n);
        for i in 0..n {
            let idx = (self.write_pos + self.window_size - n + i) % self.window_size;
            result.push(self.samples[idx]);
        }
        result
    }
}
